// Resource hooks are generated by macros for future use
#![allow(dead_code)]

use crate::hooks::use_cluster::ClusterContext;
use dioxus::prelude::*;
use k8s_openapi::api::apps::v1::{DaemonSet, Deployment, StatefulSet};
use k8s_openapi::api::batch::v1::{CronJob, Job};
use k8s_openapi::api::core::v1::{
    ConfigMap, Endpoints, Event, PersistentVolume, PersistentVolumeClaim, Pod, Secret, Service,
};
use k8s_openapi::api::networking::v1::Ingress;
use k8s_openapi::api::storage::v1::StorageClass;

#[derive(Clone, Default)]
pub struct ResourceState<T> {
    pub items: Vec<T>,
    #[allow(dead_code)]
    pub loading: bool,
    #[allow(dead_code)]
    pub error: Option<String>,
}

/// Macro to generate resource hooks for namespaced resources
macro_rules! namespaced_resource_hook {
    ($fn_name:ident, $type:ty, $client_method:ident) => {
        pub fn $fn_name(
            cluster: Signal<Option<ClusterContext>>,
            namespace: Signal<Option<String>>,
        ) -> Signal<ResourceState<$type>> {
            let mut state = use_signal(ResourceState::default);

            use_effect(move || {
                let cluster_value = cluster.read().clone();
                let namespace_value = namespace.read().clone();

                spawn(async move {
                    if let Some(ctx) = cluster_value {
                        state.set(ResourceState {
                            items: vec![],
                            loading: true,
                            error: None,
                        });

                        // Filter out empty strings - treat Some("") as None
                        let ns_ref = namespace_value.as_deref().filter(|s| !s.is_empty());
                        match ctx.client.$client_method(ns_ref).await {
                            Ok(items) => {
                                state.set(ResourceState {
                                    items,
                                    loading: false,
                                    error: None,
                                });
                            }
                            Err(e) => {
                                tracing::error!("Error fetching {}: {}", stringify!($type), e);
                                state.set(ResourceState {
                                    items: vec![],
                                    loading: false,
                                    error: Some(e.to_string()),
                                });
                            }
                        }
                    }
                });
            });

            state
        }
    };
}

/// Macro to generate resource hooks for cluster-scoped resources (no namespace)
macro_rules! cluster_scoped_resource_hook {
    ($fn_name:ident, $type:ty, $client_method:ident) => {
        pub fn $fn_name(cluster: Signal<Option<ClusterContext>>) -> Signal<ResourceState<$type>> {
            let mut state = use_signal(ResourceState::default);

            use_effect(move || {
                let cluster_value = cluster.read().clone();

                spawn(async move {
                    if let Some(ctx) = cluster_value {
                        state.set(ResourceState {
                            items: vec![],
                            loading: true,
                            error: None,
                        });

                        match ctx.client.$client_method().await {
                            Ok(items) => {
                                state.set(ResourceState {
                                    items,
                                    loading: false,
                                    error: None,
                                });
                            }
                            Err(e) => {
                                tracing::error!("Error fetching {}: {}", stringify!($type), e);
                                state.set(ResourceState {
                                    items: vec![],
                                    loading: false,
                                    error: Some(e.to_string()),
                                });
                            }
                        }
                    }
                });
            });

            state
        }
    };
}

// Generate hooks for namespaced resources
namespaced_resource_hook!(use_pods, Pod, list_pods);
namespaced_resource_hook!(use_deployments, Deployment, list_deployments);
namespaced_resource_hook!(use_statefulsets, StatefulSet, list_statefulsets);
namespaced_resource_hook!(use_daemonsets, DaemonSet, list_daemonsets);
namespaced_resource_hook!(use_cronjobs, CronJob, list_cronjobs);
namespaced_resource_hook!(use_jobs, Job, list_jobs);
namespaced_resource_hook!(use_configmaps, ConfigMap, list_configmaps);
namespaced_resource_hook!(use_services, Service, list_services);
namespaced_resource_hook!(use_secrets, Secret, list_secrets);
namespaced_resource_hook!(use_endpoints, Endpoints, list_endpoints);
namespaced_resource_hook!(use_ingresses, Ingress, list_ingresses);
namespaced_resource_hook!(
    use_persistentvolumeclaims,
    PersistentVolumeClaim,
    list_persistentvolumeclaims
);
namespaced_resource_hook!(use_events, Event, list_events);

// Generate hooks for cluster-scoped resources
cluster_scoped_resource_hook!(
    use_persistentvolumes,
    PersistentVolume,
    list_persistentvolumes
);
cluster_scoped_resource_hook!(use_storageclasses, StorageClass, list_storageclasses);
