{{- if and .Values.kubeconfigs (not .Values.existingKubeConfigSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubestudio.fullname" . }}-kubeconfig
  labels:
    {{- include "kubestudio.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.kubeconfigs }}
  {{ $key }}: |
    {{- $value | nindent 4 }}
  {{- end }}
{{- end }}
